version: '2.1'

services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/favourite-things-test-task-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=4167004
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4167004
      POSTGRES_DB: favourite-things-test-task-db
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
